version: "3.8"
services:
    server:
        build:
            dockerfile: "./dev/Dockerfile.dev"
        container_name: deep-bun-blue
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public&connect_timeout=300
        volumes:
            - ./:/app
    postgres:
        container_name: postgres
        image: postgres:14
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5434:5432
        restart: always
