###################################################################################################
# Base image for development
###################################################################################################
FROM node:16-alpine AS development

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Copy Prisma
COPY /prisma .

COPY .env .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

RUN npx prisma generate

# Expose the port the application will listen on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]
